apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - bunny-plus
  - home-assistant
  - jellyfin
  - mariadb
  - mosquitto
  - music-assistant
  - radarr
  - seerr
  - seafile
  - sonarr
  - transmission
  - zigbee2mqtt
