apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale
  namespace: flux-system
spec:
  interval: 1h
  url: https://pkgs.tailscale.com/helmcharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  chart:
    spec:
      chart: tailscale-operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
      version: 1.96.5
  install:
    remediation:
      retries: 3
  interval: 30m
  releaseName: tailscale-operator
  upgrade:
    remediation:
      retries: 3
  values:
    operatorConfig:
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          cpu: 250m
          memory: 256Mi
    proxyConfig:
      defaultProxyClass: default
  valuesFrom:
    - kind: Secret
      name: tailscale-operator-values
