apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: grafana
  namespace: monitoring
  labels:
    kubernetes.io/service-name: grafana
addressType: IPv4
endpoints:
  - addresses:
      - 192.168.1.240
ports:
  - name: http
    port: 3000
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    tailscale.com/hostname: "grafana"
    tailscale.com/tags: "tag:k8s"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: grafana
      port:
        number: 3000
  tls:
    - hosts:
        - grafana
