#!/bin/bash
# lemonbar config

# colour scheme
COLOR_00='#2b303b'
COLOR_01='#bf616a'
COLOR_02='#a3be8c'
COLOR_03='#ebcb8b'
COLOR_04='#8fa1b3'
COLOR_05='#b48ead'
COLOR_06='#96b5b4'
COLOR_07='#c0c5ce'
COLOR_08='#65737e'
COLOR_09='#bf616a'
COLOR_0A='#a3be8c'
COLOR_0B='#ebcb8b'
COLOR_0C='#8fa1b3'
COLOR_0D='#b48ead'
COLOR_0E='#96b5b4'
COLOR_0F='#eff1f5'

# add extra for alpha
COLOR_TRANS="#00000000"
COLOR_AA00="$(echo $COLOR_00 | sed 's/#/#FF/g')"
COLOR_AA01="$(echo $COLOR_01 | sed 's/#/#FF/g')"
COLOR_AA02="$(echo $COLOR_02 | sed 's/#/#FF/g')"
COLOR_AA03="$(echo $COLOR_03 | sed 's/#/#FF/g')"
COLOR_AA04="$(echo $COLOR_04 | sed 's/#/#FF/g')"
COLOR_AA05="$(echo $COLOR_05 | sed 's/#/#FF/g')"
COLOR_AA06="$(echo $COLOR_06 | sed 's/#/#FF/g')"
COLOR_AA07="$(echo $COLOR_07 | sed 's/#/#FF/g')"
COLOR_AA08="$(echo $COLOR_08 | sed 's/#/#FF/g')"
COLOR_AA09="$(echo $COLOR_09 | sed 's/#/#FF/g')"
COLOR_AA0A="$(echo $COLOR_0A | sed 's/#/#FF/g')"
COLOR_AA0B="$(echo $COLOR_0B | sed 's/#/#FF/g')"
COLOR_AA0C="$(echo $COLOR_0C | sed 's/#/#FF/g')"
COLOR_AA0D="$(echo $COLOR_0D | sed 's/#/#FF/g')"
COLOR_AA0E="$(echo $COLOR_0E | sed 's/#/#FF/g')"
COLOR_AA0F="$(echo $COLOR_0F | sed 's/#/#FF/g')"

# set font
FONT_1="M+ 1m:size=13"
FONT_2="Noto Serif CJK KR:size=13"
FONT_3="Material Icons:size=18"

# panel geometry widthxheight+x+y
PANEL_GEOMETRY="3440x35"

# panel icons
PANEL_BSPWM_ICON_F_O_D=""		# focused occupied desktop
PANEL_BSPWM_ICON_F_F_D=""		# focused free desktop
PANEL_BSPWM_ICON_F_U_D=""		# focused urgent desktop
PANEL_BSPWM_ICON_O_D=""		# occupied desktop
PANEL_BSPWM_ICON_F_D=""		# free desktop
PANEL_BSPWM_ICON_U_D=""	# urgent desktop