#!/bin/bash
# lemonbar config

# colour scheme
COLOR_00='#2b303b'
COLOR_01='#bf616a'
COLOR_02='#a3be8c'
COLOR_03='#ebcb8b'
COLOR_04='#8fa1b3'
COLOR_05='#b48ead'
COLOR_06='#96b5b4'
COLOR_07='#c0c5ce'
COLOR_08='#65737e'
COLOR_09='#bf616a'
COLOR_0A='#a3be8c'
COLOR_0B='#ebcb8b'
COLOR_0C='#8fa1b3'
COLOR_0D='#b48ead'
COLOR_0E='#96b5b4'
COLOR_0F='#eff1f5'
COLOR_TRANS="#00000000"

# add extra for alpha
COLOR_AA00="${COLOR_00//#/#FF}"
COLOR_AA01="${COLOR_01//#/#FF}"
COLOR_AA02="${COLOR_02//#/#FF}"
COLOR_AA03="${COLOR_03//#/#FF}"
COLOR_AA04="${COLOR_04//#/#FF}"
COLOR_AA05="${COLOR_05//#/#FF}"
COLOR_AA06="${COLOR_06//#/#FF}"
COLOR_AA07="${COLOR_07//#/#FF}"
COLOR_AA08="${COLOR_08//#/#FF}"
COLOR_AA09="${COLOR_09//#/#FF}"
COLOR_AA0A="${COLOR_0A//#/#FF}"
COLOR_AA0B="${COLOR_0B//#/#FF}"
COLOR_AA0C="${COLOR_0C//#/#FF}"
COLOR_AA0D="${COLOR_0D//#/#FF}"
COLOR_AA0E="${COLOR_0E//#/#FF}"
COLOR_AA0F="${COLOR_0F//#/#FF}"

# set font
FONT_1="M+ 1m:size=13"
FONT_2="Noto Serif CJK KR:size=13"
FONT_3="Material Icons:size=18"

# panel geometry widthxheight+x+y
PANEL_GEOMETRY="3440x35+1440"

# panel icons
PANEL_BSPWM_ICON_F_O_D=""		# focused occupied desktop
PANEL_BSPWM_ICON_F_F_D=""		# focused free desktop
PANEL_BSPWM_ICON_F_U_D=""		# focused urgent desktop
PANEL_BSPWM_ICON_O_D=""		# occupied desktop
PANEL_BSPWM_ICON_F_D=""		# free desktop
PANEL_BSPWM_ICON_U_D=""	# urgent desktop