#!/bin/bash
# sxhkdrc

# bspwm hotkeys

# presel the direction
super + shift + {Up,Left,Right,Down}
    bspc node -p {~north,~west,~east,~south}

# presel the ratio
super + ctrl + {1-9}
    bspc node -o 0.{1-9}

# quit bspwm normally
super + alt + Escape
    bspc quit

# close and kill
super + {_,shift + } w
    bspc node -{c,k}

# state/flags

# set the window state
super + {t,shift + t,s,f}
    bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {x,y,z}
    bspc node -g {locked,sticky,private}

# focus/swap

# focus the node in the given direction
super + {Up,Left,Right,Down}
    bspc node -f {north,west,east,south}

# focus the last node/desktop
super + {grave,Tab}
    bspc {node,desktop} -f last

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
    bspc {desktop -f,node -d} '^{1-9,10}'

# browser
super + o
    $BROWSER &

# terminal emulator
super + Return
    termite &

# program launcher
super + space
    source "$HOME"/.zshenv && rofi -show run &

# printscreen
Print
    ~/bin/charlotta &

# reload all our configuration files
super + Escape
    pkill -USR1 -x sxhkd

# log out from user session
super + ctrl + Escape
    zenity --question --text 'Are you sure you want to log-out?' && bspc quit && kill -s TERM "$(cat /tmp/panel-pid)"
    #rofi -show fb -modi fb:~/bin/power-management

# media
XF86Audio{Raise,Lower}Volume
    amixer set Master -i 5%{+,-} &
XF86Audio{Prev,Next,Play}
    mpc -h ~/.config/mpd/socket -q {prev,next,toggle} &

# toggle keyboard layout (fn + y)
XF86Calculator
    (setxkbmap -query | grep -q "layout:\s\+us") && setxkbmap se || setxkbmap us