#!/bin/bash
source $XDG_CONFIG_HOME/themes/config
while read -r line ; do
	case $line in
		S*)
			# conky
			conky="${line#?} "
			;;
		T*)
			# xtitle
			#title="%{F$COLOR_0E_aa}%{B$COLOR_07_aa} ${line#?} %{B-}%{F-}"
			;;
		W*)
			# bspwm
			bspwm=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					O*)	# focused occupied desktop
					if [[ $name == "tv" ]]; then #ignoring if the desktop is called tv
						bspwm="${bspwm}"
					else
						bspwm="${bspwm}%{F$COLOR_0E_aa}%{B$COLOR_07_aa} $PANEL_BSPWM_ICON_F_O_D %{B-}%{F-}"
					fi
					;;

					F*)	# focused free desktop
					if [[ $name == "tv" ]]; then #ignoring if the desktop is called tv
						bspwm="${bspwm}"
					else
						bspwm="${bspwm}%{F$COLOR_0E_aa}%{B$COLOR_07_aa} $PANEL_BSPWM_ICON_F_F_D %{B-}%{F-}"
					fi
					;;

					U*)	# focused urgent desktop
					if [[ $name == "tv" ]]; then #ignoring if the desktop is called tv
						bspwm="${bspwm}"
					else
						bspwm="${bspwm}%{F$COLOR_0E_aa}%{B$COLOR_07_aa} $PANEL_BSPWM_ICON_F_U_D {B-}%{F-}"
					fi
					;;

					o*)	# occupied desktop
					if [[ $name == "tv" ]]; then #ignoring if the desktop is called tv
						bspwm="${bspwm}"
					else
						bspwm="${bspwm}%{F$COLOR_0E_aa}%{B$COLOR_07_aa} $PANEL_BSPWM_ICON_O_D %{B-}%{F-}"
					fi
					;;

					f*)	# free desktop
					if [[ $name == "tv" ]]; then #ignoring if the desktop is called tv
						bspwm="${bspwm}"
					else
						bspwm="${bspwm}%{F$COLOR_0E_aa}%{B$COLOR_07_aa} $PANEL_BSPWM_ICON_F_D %{B-}%{F-}"
					fi
					;;

					u*) # urgent desktop
					if [[ $name == "tv" ]]; then #ignoring if the desktop is called tv
						bspwm="${bspwm}"
					else
						bspwm="${bspwm}%{F$COLOR_0E_aa}%{B$COLOR_07_aa} $PANEL_BSPWM_ICON_U_D %{B-}%{F-}"
					fi
					;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{l}${title}%{c}${bspwm}%{r}${conky}"
done
