#!/bin/bash
cd $(dirname $0)
source $XDG_CONFIG_HOME/themes/config

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc control --subscribe > "$PANEL_FIFO" &
conky -c panel_conky > "$PANEL_FIFO" &

cat "$PANEL_FIFO" \
	| $SCRIPTS/panel/panel_bar \
	| lemonbar \
		-f "$FONT_1" \
		-f "$FONT_2" \
		-F "$COLOR_AA04" \
		-B "#00" \
		-g "$PANEL_GEOMETRY" | \
		while read line; do
   			panel_execute $line
		done &
wait
