#!/bin/bash
# shitty lemonbar border hack
source $XDG_CONFIG_HOME/themes/config

panel_width="$(echo "$PANEL_GEOMETRY" | grep -Eo '[0-9]{1,4}' | head -n1)"
panel_height="$(echo "$PANEL_GEOMETRY" | grep -Eo '[0-9]{1,4}' | head -n2 | tail -1)"
panel_x="$(echo "$PANEL_GEOMETRY" | grep -Eo '[0-9]{1,4}' | head -n3 | tail -1)"
panel_y="$(echo "$PANEL_GEOMETRY" | grep -Eo '[0-9]{1,4}' | head -n4 | tail -1)"
panel_bg_width=$((panel_width + 6))
panel_bg_height=$((panel_height + 6))
panel_bg_x=$((panel_x - 3))
panel_bg_y=$((panel_y - 3))

cat "/dev/null" \
	| bar -p -g "${panel_bg_width}""x""${panel_bg_height}"+"${panel_bg_x}"+"${panel_bg_y}" -B "$COLOR_0E_aa"
wait