#!/bin/bash
# themes
# base16 ocean light
COLOR_00='#2b303b'
COLOR_01='#343d46'
COLOR_02='#4f5b66'
COLOR_03='#65737e'
COLOR_04='#a7adba'
COLOR_05='#c0c5ce'
COLOR_06='#dfe1e8'
COLOR_07='#eff1f5'
COLOR_08='#bf616a'
COLOR_09='#d08770'
COLOR_0A='#ebcb8b'
COLOR_0B='#a3be8c'
COLOR_0C='#96b5b4'
COLOR_0D='#8fa1b3'
COLOR_0E='#b48ead'
COLOR_0F='#ab7967'