#!/bin/bash
# themes
# base16 ocean light
COLOR_00='#2b303b'
COLOR_01='#bf616a'
COLOR_02='#a3be8c'
COLOR_03='#ebcb8b'
COLOR_04='#8fa1b3'
COLOR_05='#b48ead'
COLOR_06='#96b5b4'
COLOR_07='#c0c5ce'
COLOR_08='#65737e'
COLOR_09='#bf616a'
COLOR_0A='#a3be8c'
COLOR_0B='#ebcb8b'
COLOR_0C='#8fa1b3'
COLOR_0D='#b48ead'
COLOR_0E='#96b5b4'
COLOR_0F='#eff1f5'