#!/bin/bash
# themes

# set overall theme
source $XDG_CONFIG_HOME/themes/base16-ocean

# add extra for alpha
COLOR_AA00="$(echo $COLOR_00 | sed 's/#/#FF/g')"
COLOR_AA01="$(echo $COLOR_01 | sed 's/#/#FF/g')"
COLOR_AA02="$(echo $COLOR_02 | sed 's/#/#FF/g')"
COLOR_AA03="$(echo $COLOR_03 | sed 's/#/#FF/g')"
COLOR_AA04="$(echo $COLOR_04 | sed 's/#/#FF/g')"
COLOR_AA05="$(echo $COLOR_05 | sed 's/#/#FF/g')"
COLOR_AA06="$(echo $COLOR_06 | sed 's/#/#FF/g')"
COLOR_AA07="$(echo $COLOR_07 | sed 's/#/#FF/g')"
COLOR_AA08="$(echo $COLOR_08 | sed 's/#/#FF/g')"
COLOR_AA09="$(echo $COLOR_09 | sed 's/#/#FF/g')"
COLOR_AA0A="$(echo $COLOR_0A | sed 's/#/#FF/g')"
COLOR_AA0B="$(echo $COLOR_0B | sed 's/#/#FF/g')"
COLOR_AA0C="$(echo $COLOR_0C | sed 's/#/#FF/g')"
COLOR_AA0D="$(echo $COLOR_0D | sed 's/#/#FF/g')"
COLOR_AA0E="$(echo $COLOR_0E | sed 's/#/#FF/g')"
COLOR_AA0F="$(echo $COLOR_0F | sed 's/#/#FF/g')"

# set font
FONT_1="M+ 2m regular:size=9"
FONT_2="FontAwesome:size=12"

# panel geometry, notify/dmenu inherits the geometry from this
PANEL_GEOMETRY="1904x25+8+9"

# panel icons
PANEL_BSPWM_ICON_F_O_D=""		# focused occupied desktop
PANEL_BSPWM_ICON_F_F_D=""		# focused free desktop
PANEL_BSPWM_ICON_F_U_D=""		# focused urgent desktop
PANEL_BSPWM_ICON_O_D=""		# occupied desktop
PANEL_BSPWM_ICON_F_D=""		# free desktop
PANEL_BSPWM_ICON_U_D=""		# urgent desktop
