#!/bin/bash
# themes

# set overall theme
source $XDG_CONFIG_HOME/themes/base16-ocean

# set font
FONT_1="M+ 2m regular:size=9"
FONT_2="FontAwesome:size=12"

# panel geometry, notify/dmenu inherits the geometry from this
PANEL_GEOMETRY="1904x25+8+9"

# panel icons
PANEL_BSPWM_ICON_F_O_D=""		# focused occupied desktop
PANEL_BSPWM_ICON_F_F_D=""		# focused free desktop
PANEL_BSPWM_ICON_F_U_D=""		# focused urgent desktop
PANEL_BSPWM_ICON_O_D=""		# occupied desktop
PANEL_BSPWM_ICON_F_D=""		# free desktop
PANEL_BSPWM_ICON_U_D=""		# urgent desktop
