apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/gotk-components.yaml
  - flux-system/discord.sops.yaml
  - flux-system/notifications.yaml
  - flux-system/sops-check.sops.yaml
  - flux-system/gotk-sync.yaml
  - infrastructure
  - applications
