apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - caddy
  - hermes-agent
  - home-assistant
  - jellyfin
  - mosquitto
  - music-assistant
  - radarr
  - seerr
  - sonarr
  - transmission
  - zigbee2mqtt
