#!/bin/bash
# bspwmrc
set -a

# cursor settings
bspc config pointer_modifier        mod4
bspc config pointer_action1         move
bspc config pointer_action2         resize_side
bspc config pointer_action3         resize_corner
bspc config focus_follows_pointer   true

# border colours
bspc config focused_border_color    "#b48ead"
bspc config active_border_color     "#96b5b4"
bspc config normal_border_color     "#8fa1b3"
bspc config presel_feedback_color   "#b48ead"

# pretty things
bspc config split_ratio             0.5
bspc config top_padding             40
bspc config border_width            4
bspc config window_gap              15
bspc config borderless_monocle      true
bspc config gapless_monocle         true
# potrait monitor
bspc config -m DVI-I-1 top_padding  0

# set up desktops
bspc monitor DP-1 -d                1 2 3 4 5
bspc monitor DVI-I-1 -d             portrait
bspc monitor HDMI-0 -d              tv
bspc wm -O                          DP-1 DV-I-1 HDMI-0

# application specific rules
# wine desktop
bspc rule -a explorer.exe desktop=5 &
# games
bspc rule -a gw2-64.exe desktop=5 locked=on &
# floating
bspc rule -a Pinentry state=floating &
bspc rule -a Library state=floating &
# libreoffice doesn't behave after opening a new file
bspc rule -a '*:libreofficedev' state=tiled &
bspc rule -a '*:soffice' state=tiled &
# kodi
bspc rule -a '*:Kodi' desktop=tv state=fullscreen &

# set up panel
kill -s TERM $(cat /tmp/panel-pid) 2>/dev/null & ~/.config/lemonbar/panel &

# weird workaround, hidpi gtk bullshit? need to investigate why spawning lxappearance for a sec fixes it
bspc rule -a  '*:lxappearance' desktop=5 &
lxappearance & sleep 1 && pkill lxappearance