#!/bin/bash
# bspwmrc
set -a

# cursor settings
bspc config pointer_modifier        mod4
bspc config pointer_action1         move
bspc config pointer_action2         resize_side
bspc config pointer_action3         resize_corner
bspc config focus_follows_pointer   true

# border colours
bspc config focused_border_color    "#b48ead"
bspc config active_border_color     "#96b5b4"
bspc config normal_border_color     "#8fa1b3"
bspc config presel_feedback_color   "#b48ead"

# pretty things
bspc config split_ratio             0.5
bspc config top_padding             40
bspc config border_width            4
bspc config window_gap              15
bspc config borderless_monocle      true
bspc config gapless_monocle         true

# potrait monitor
bspc config -m DP-2 top_padding 0

# set up desktops
bspc monitor USB-C-0 -d                1 2 3 4 5
bspc monitor HDMI-0 -d                6 7
bspc wm -O                          USB-C-0 HDMI-0
bspc config remove_disabled_monitors false
bspc config remove_unplugged_monitors false
bspc config merge_overlapping_monitors false

# application specific rules
# wine desktop
bspc rule -a explorer.exe desktop=5 &
# games
bspc rule -a gw2-64.exe desktop=5 locked=on &
# floating
bspc rule -a Pinentry state=floating &
bspc rule -a Library state=floating &
# libreoffice doesn't behave after opening a new file
bspc rule -a '*:libreofficedev' state=tiled &
bspc rule -a '*:soffice' state=tiled &
bspc rule -a '*:Steam' desktop=4 follow=no &
# kodi
bspc rule -a '*:Kodi' desktop=tv state=fullscreen &
# firefox
bspc rule -a 'Nightly':Navigator state=tiled &
bspc rule -a 'Nightly':Places state=floating &
bspc rule -a 'Nightly':Popup state=floating border=off &
bspc rule -a 'Nightly':Prompt state=floating &

bspc rule -a 'Wine':fl64.exe state=tiled &

# set up panel
kill -s TERM $"(cat /tmp/panel-pid)" 2>/dev/null & ~/.config/lemonbar/panel &
